# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The PHD Mole
email: mole@nissc.33mail.com
description: >- # this means to ignore newlines until "baseurl:"
  Um, hi. So, I'm a PHD-student in natural language processing at a European university, and I'm technically also a mole, but probably not in the derivative meaning you might initially think about.
  I just happen to be blind, which also, incidentally, would make me either a horrible spy or an awesome one, depending on the purposes.
  As it happens, the purposes of the current work I do as a self-appointed PHD mole, apart from exploring computational linguistics approaches to hyperbole detection, obviously, is to spy on myself and my learning process continuously in order to make sure that it isn't getting tampered with by too much imposter syndrome, perfectionism, or miscellaneous accessibility issues as a consequence of my blindness.
  In this blog, I plan to cover a variety of aspects of PHD life, from interesting research topics, to less private rants about challenges I encounter. Some of the posts might be about my own work or interesting subfields or research within linguistics/natural language processing/machine learning that I become aware of, but others might also just be about documenting the PHD journey with blindness in order to be a resource for anyone who might wish to proceed me. Have fun reading!
baseurl: "blog" # the subpath of your site, e.g. /blog
url: "http://PHDMole." # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
